file_path: './data/regression_bonus_practice_data.csv'
target_column: final_test
val_test_size: 0.3
val_size: 0.67
param_grid:
  regressor__alpha: [0.1, 1, 10, 100, 1000]
  regressor__fit_intercept: [True, False]
cv: 5
scoring: r2
numerical_features:
  - total_classmates 
  - hours_per_week 
  - attendance_rate 
  - number_of_siblings
nominal_features:
  - CCA 
  - learning_style
ordinal_features:
  - direct_admission 
  - tuition 
  - sleep_time
passthrough_features:
